version: "3.8"

services:

  indexer:
    build:
      context: ../..
      dockerfile: demo_tzbtc/docker/Dockerfile
    depends_on:
      - db
    volumes:
      - ../dipdup.yml:/home/dipdup/dipdup.yml
      - ../dipdup-docker.yml:/home/dipdup/dipdup-docker.yml
    command: ['-c', 'dipdup.yml', '-c', 'dipdup-docker.yml', 'run']
    restart: always
    env_file: dipdup.env

  db:
    image: postgres:13
    ports:
      - 127.0.0.1:5432:5432
    restart: always
    volumes:
      - db:/var/lib/postgres/data
    env_file: dipdup.env 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  hasura:
    image: hasura/graphql-engine:v2.4.0
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - db
    restart: always
    env_file: dipdup.env
  
volumes:
  db: