# Run `dipdup new --replay configs/replay.yaml` to generate new project from this replay
spec_version: 2.0
replay:
  dipdup_version: 7
  template: demo_token_transfers
  package: demo_token_transfers
  version: 0.0.1
  description: TzBTC FA1.2 token transfers
  license: MIT
  name: John Doe
  email: john_doe@example.com
  postgres_image: postgres:15
  postgres_data_path: /var/lib/postgresql/data
  hasura_image: hasura/graphql-engine:latest
  line_length: 120
